name: haskell1a
version: 0.1.0.0

dependencies:
  - base
  - containers

library:
  exposed-modules: Haskell1A
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - haskell1a
      - hspec
